collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8675373
color:
  saturation: 0.4137485
  brandStrength: 0.8626038
  rhythmicContrast: 0.8252006
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#2C2C2C'
    - '#565656'
    - '#A1A1A1'
  lightness: 0.3098094
layout_spectrum: 1
name: ClassicalBye
