collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7066231
  brandStrength: 0.09141791
  lightness: 0.3120336
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#2C2C2C'
    - '#565656'
    - '#A1A1A1'
  rhythmicContrast: 0.8255597
typography_spectrum: 0.8675373
layout_spectrum: 0.900653
name: ClassicalBye
