collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4937343
  brandStrength: 0.790112
  lightness: 0.2286967
  brandColors:
    - '#110708'
    - '#FFFFFF'
    - '#FF082B'
    - '#B1C3F3'
    - '#5E4E42'
  rhythmicContrast: 0.6610276
typography_spectrum: 0.8675373
layout_spectrum: 0.900653
name: ClassicalBye
